INSTALL_AUR_OPTIONAL=true
INSTALL_BLUETOOTH=true
INSTALL_SSH=true
INSTALL_SOCIAL=true
INSTALL_SPOTIFY=true
INSTALL_WHATSAPP=true
INSTALL_FILEMANAGER=true
INSTALL_DEVELOPMENT=true
INSTALL_POWERTOOLS=false
INSTALL_AUR=true