INSTALL_AUR=false
INSTALL_BLUETOOTH=false
INSTALL_DESKTOP=false
INSTALL_SSH=true
INSTALL_SOCIAL=false
INSTALL_SPOTIFY=false
INSTALL_WHATSAPP=false
INSTALL_FILEMANAGER=false
INSTALL_DEVELOPMENT=false
INSTALL_POWERTOOLS=false
